### PR TITLE
Add route for container network

### PR DESCRIPTION
**Pull request by gavrie**
The container network seems to always be 172.20.0.0/16, so this PR adds the route to there automatically.

### CODE REVIEW

**Comment by jwundrak** [comment]
For me the default Network 172.18/16. Docker tried to miss a conflict.

There should be a detection. To get all routings, you can use: https://github.com/jwundrak/docker-tuntap-osx/blob/osx-routing/sbin/docker_tap_up.sh

**Comment by gavrie** [comment]
> For me the default Network 172.18/16. Docker tried to miss a conflict.
> 
> There should be a detection. To get all routings, you can use: https://github.com/jwundrak/docker-tuntap-osx/blob/osx-routing/sbin/docker_tap_up.sh

@jwundrak You're right, this was just an artifact of my specific configuration.
I'll use your fork, thanks!

**Comment by jwundrak** [comment]
But this not the "everything-works"-solution. In my company there are multiple conflicts through e.g VPN. It is more difficult...
Personally it add the required routes after a reboot (cmd + r)

**Comment by gavrie** [comment]
@jwundrak would you try getting your changes merged upstream? It would be nice to have one version instead of multiple forks.

**Comment by jwundrak** [comment]
@gavrie Look at my response. It is not mergable for all. To specific.
There must be a "what subnets I can use"-logic. But this is not easy...

**Comment by gavrie** [comment]
> @gavrie Look at my response. It is not mergable for all. To specific.
> There must be a "what subnets I can use"-logic. But this is not easy...

Yeah, we commented at about the same time 😄.
I agree, this is more complicated than what it first seems.
I see there are several forks; the most updated based on yours and merged with the upstream seems to be https://github.com/smoke/docker-tuntap-osx.

**Pull request closed without merging**
